# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-06 07:39
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('BeliefDivergence', '0006_auto_20181206_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='Green_Urn_Given',
            field=otree.db.models.FloatField(null=True),
        ),
    ]
