# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-26 19:16
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_matching_pennies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_winner',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
    ]
