# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-18 11:46
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_test_game', '0003_auto_20181018_0742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='response1',
        ),
        migrations.AddField(
            model_name='player',
            name='response',
            field=otree.db.models.FloatField(null=True, verbose_name=''),
        ),
    ]
