# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-18 11:54
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_test_game', '0004_auto_20181018_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='left',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='right',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
