# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-26 17:19
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_test_game', '0007_auto_20181025_0231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='age',
        ),
        migrations.RemoveField(
            model_name='player',
            name='left',
        ),
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='response',
        ),
        migrations.RemoveField(
            model_name='player',
            name='response2',
        ),
        migrations.RemoveField(
            model_name='player',
            name='right',
        ),
        migrations.AddField(
            model_name='player',
            name='my_hidden_input',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
