# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-26 17:24
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_test_game', '0008_auto_20181126_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='my_hidden_input',
        ),
        migrations.AddField(
            model_name='player',
            name='G1',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='R1',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='Y1',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
