# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-26 23:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models
import otree_save_the_change.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('otree', '0002_session_mturk_expiration'),
        ('my_test_game', '0010_auto_20181126_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('R1', otree.db.models.IntegerField(null=True)),
                ('Y1', otree.db.models.IntegerField(null=True)),
                ('G1', otree.db.models.IntegerField(null=True)),
                ('R2', otree.db.models.IntegerField(null=True)),
                ('Y2', otree.db.models.IntegerField(null=True)),
                ('G2', otree.db.models.IntegerField(null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_test_game.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_test_game_player2', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_test_game_player2', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_test_game.Subsession')),
            ],
            options={
                'db_table': 'my_test_game_player2',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
    ]
