# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-26 23:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_test_game', '0011_player2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player2',
            name='group',
        ),
        migrations.RemoveField(
            model_name='player2',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='player2',
            name='session',
        ),
        migrations.RemoveField(
            model_name='player2',
            name='subsession',
        ),
        migrations.DeleteModel(
            name='Player2',
        ),
    ]
