# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-29 13:45
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_test_game', '0012_auto_20181126_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='isGray',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
    ]
