# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-01 05:34
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_test_game', '0013_player_isgray'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='Accuracy1',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
