# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-04 20:32
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_test_game', '0015_auto_20181204_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='isGray1',
        ),
        migrations.AddField(
            model_name='player',
            name='isGray',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
    ]
