# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-04 20:44
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_test_game', '0018_auto_20181204_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='G1_task2',
        ),
        migrations.RemoveField(
            model_name='player',
            name='R1_task2',
        ),
        migrations.RemoveField(
            model_name='player',
            name='Y1_task2',
        ),
        migrations.AddField(
            model_name='player',
            name='G1task2',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='R1task2',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='Y1task2',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
