# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-04 21:03
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_test_game', '0019_auto_20181204_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='Accuracy1Task2',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
